"""initial schema: all Phase 1-5 tables, pgvector extension, HNSW index

Revision ID: 0001
Revises:
Create Date: 2026-09-25

The baseline is built from the SQLAlchemy metadata snapshot so every table
stays in lock-step with the models; later revisions are autogenerated diffs.
"""
from alembic import op

from app.models import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    Base.metadata.create_all(bind=bind)
    if bind.dialect.name == "postgresql":
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_documents_embedding_hnsw ON documents "
            "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
        )


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
